// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: element_globalmsg.proto

package io.element.protobuf;

public final class GlobalProto {
  private GlobalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MESSAGE}
   */
  public enum MESSAGE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE_LOGIN_G2S = 1;</code>
     */
    MESSAGE_LOGIN_G2S(0, 1),
    /**
     * <code>MESSAGE_LOGIN_S2G = 2;</code>
     */
    MESSAGE_LOGIN_S2G(1, 2),
    /**
     * <code>MESSAGE_LOGIN_C2G = 3;</code>
     */
    MESSAGE_LOGIN_C2G(2, 3),
    /**
     * <code>MESSAGE_LOGIN_G2C = 4;</code>
     */
    MESSAGE_LOGIN_G2C(3, 4),
    /**
     * <code>MESSAGE_SIMPLE_G2S = 5;</code>
     */
    MESSAGE_SIMPLE_G2S(4, 5),
    /**
     * <code>MESSAGE_SIMPLE_S2G = 6;</code>
     */
    MESSAGE_SIMPLE_S2G(5, 6),
    /**
     * <code>MESSAGE_SIMPLE_C2G = 7;</code>
     */
    MESSAGE_SIMPLE_C2G(6, 7),
    /**
     * <code>MESSAGE_SIMPLE_G2C = 8;</code>
     */
    MESSAGE_SIMPLE_G2C(7, 8),
    ;

    /**
     * <code>MESSAGE_LOGIN_G2S = 1;</code>
     */
    public static final int MESSAGE_LOGIN_G2S_VALUE = 1;
    /**
     * <code>MESSAGE_LOGIN_S2G = 2;</code>
     */
    public static final int MESSAGE_LOGIN_S2G_VALUE = 2;
    /**
     * <code>MESSAGE_LOGIN_C2G = 3;</code>
     */
    public static final int MESSAGE_LOGIN_C2G_VALUE = 3;
    /**
     * <code>MESSAGE_LOGIN_G2C = 4;</code>
     */
    public static final int MESSAGE_LOGIN_G2C_VALUE = 4;
    /**
     * <code>MESSAGE_SIMPLE_G2S = 5;</code>
     */
    public static final int MESSAGE_SIMPLE_G2S_VALUE = 5;
    /**
     * <code>MESSAGE_SIMPLE_S2G = 6;</code>
     */
    public static final int MESSAGE_SIMPLE_S2G_VALUE = 6;
    /**
     * <code>MESSAGE_SIMPLE_C2G = 7;</code>
     */
    public static final int MESSAGE_SIMPLE_C2G_VALUE = 7;
    /**
     * <code>MESSAGE_SIMPLE_G2C = 8;</code>
     */
    public static final int MESSAGE_SIMPLE_G2C_VALUE = 8;


    public final int getNumber() { return value; }

    public static MESSAGE valueOf(int value) {
      switch (value) {
        case 1: return MESSAGE_LOGIN_G2S;
        case 2: return MESSAGE_LOGIN_S2G;
        case 3: return MESSAGE_LOGIN_C2G;
        case 4: return MESSAGE_LOGIN_G2C;
        case 5: return MESSAGE_SIMPLE_G2S;
        case 6: return MESSAGE_SIMPLE_S2G;
        case 7: return MESSAGE_SIMPLE_C2G;
        case 8: return MESSAGE_SIMPLE_G2C;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MESSAGE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MESSAGE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MESSAGE>() {
            public MESSAGE findValueByNumber(int number) {
              return MESSAGE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.element.protobuf.GlobalProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MESSAGE[] VALUES = values();

    public static MESSAGE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MESSAGE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MESSAGE)
  }

  public interface MessageStreamOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .MESSAGE type = 1;
    /**
     * <code>required .MESSAGE type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .MESSAGE type = 1;</code>
     */
    io.element.protobuf.GlobalProto.MESSAGE getType();

    // optional bytes requestData = 2;
    /**
     * <code>optional bytes requestData = 2;</code>
     */
    boolean hasRequestData();
    /**
     * <code>optional bytes requestData = 2;</code>
     */
    com.google.protobuf.ByteString getRequestData();
  }
  /**
   * Protobuf type {@code MessageStream}
   */
  public static final class MessageStream extends
      com.google.protobuf.GeneratedMessage
      implements MessageStreamOrBuilder {
    // Use MessageStream.newBuilder() to construct.
    private MessageStream(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageStream(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageStream defaultInstance;
    public static MessageStream getDefaultInstance() {
      return defaultInstance;
    }

    public MessageStream getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageStream(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              io.element.protobuf.GlobalProto.MESSAGE value = io.element.protobuf.GlobalProto.MESSAGE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              requestData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.element.protobuf.GlobalProto.internal_static_MessageStream_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.element.protobuf.GlobalProto.internal_static_MessageStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.element.protobuf.GlobalProto.MessageStream.class, io.element.protobuf.GlobalProto.MessageStream.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageStream> PARSER =
        new com.google.protobuf.AbstractParser<MessageStream>() {
      public MessageStream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageStream(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageStream> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .MESSAGE type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private io.element.protobuf.GlobalProto.MESSAGE type_;
    /**
     * <code>required .MESSAGE type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MESSAGE type = 1;</code>
     */
    public io.element.protobuf.GlobalProto.MESSAGE getType() {
      return type_;
    }

    // optional bytes requestData = 2;
    public static final int REQUESTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString requestData_;
    /**
     * <code>optional bytes requestData = 2;</code>
     */
    public boolean hasRequestData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes requestData = 2;</code>
     */
    public com.google.protobuf.ByteString getRequestData() {
      return requestData_;
    }

    private void initFields() {
      type_ = io.element.protobuf.GlobalProto.MESSAGE.MESSAGE_LOGIN_G2S;
      requestData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, requestData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, requestData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.element.protobuf.GlobalProto.MessageStream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.element.protobuf.GlobalProto.MessageStream prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageStream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.element.protobuf.GlobalProto.MessageStreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.element.protobuf.GlobalProto.internal_static_MessageStream_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.element.protobuf.GlobalProto.internal_static_MessageStream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.element.protobuf.GlobalProto.MessageStream.class, io.element.protobuf.GlobalProto.MessageStream.Builder.class);
      }

      // Construct using io.element.protobuf.GlobalProto.MessageStream.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = io.element.protobuf.GlobalProto.MESSAGE.MESSAGE_LOGIN_G2S;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.element.protobuf.GlobalProto.internal_static_MessageStream_descriptor;
      }

      public io.element.protobuf.GlobalProto.MessageStream getDefaultInstanceForType() {
        return io.element.protobuf.GlobalProto.MessageStream.getDefaultInstance();
      }

      public io.element.protobuf.GlobalProto.MessageStream build() {
        io.element.protobuf.GlobalProto.MessageStream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.element.protobuf.GlobalProto.MessageStream buildPartial() {
        io.element.protobuf.GlobalProto.MessageStream result = new io.element.protobuf.GlobalProto.MessageStream(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestData_ = requestData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.element.protobuf.GlobalProto.MessageStream) {
          return mergeFrom((io.element.protobuf.GlobalProto.MessageStream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.element.protobuf.GlobalProto.MessageStream other) {
        if (other == io.element.protobuf.GlobalProto.MessageStream.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRequestData()) {
          setRequestData(other.getRequestData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.element.protobuf.GlobalProto.MessageStream parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.element.protobuf.GlobalProto.MessageStream) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .MESSAGE type = 1;
      private io.element.protobuf.GlobalProto.MESSAGE type_ = io.element.protobuf.GlobalProto.MESSAGE.MESSAGE_LOGIN_G2S;
      /**
       * <code>required .MESSAGE type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .MESSAGE type = 1;</code>
       */
      public io.element.protobuf.GlobalProto.MESSAGE getType() {
        return type_;
      }
      /**
       * <code>required .MESSAGE type = 1;</code>
       */
      public Builder setType(io.element.protobuf.GlobalProto.MESSAGE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MESSAGE type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = io.element.protobuf.GlobalProto.MESSAGE.MESSAGE_LOGIN_G2S;
        onChanged();
        return this;
      }

      // optional bytes requestData = 2;
      private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes requestData = 2;</code>
       */
      public boolean hasRequestData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes requestData = 2;</code>
       */
      public com.google.protobuf.ByteString getRequestData() {
        return requestData_;
      }
      /**
       * <code>optional bytes requestData = 2;</code>
       */
      public Builder setRequestData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes requestData = 2;</code>
       */
      public Builder clearRequestData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageStream)
    }

    static {
      defaultInstance = new MessageStream(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageStream)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageStream_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027element_globalmsg.proto\"<\n\rMessageStre" +
      "am\022\026\n\004type\030\001 \002(\0162\010.MESSAGE\022\023\n\013requestDat" +
      "a\030\002 \001(\014*\305\001\n\007MESSAGE\022\025\n\021MESSAGE_LOGIN_G2S" +
      "\020\001\022\025\n\021MESSAGE_LOGIN_S2G\020\002\022\025\n\021MESSAGE_LOG" +
      "IN_C2G\020\003\022\025\n\021MESSAGE_LOGIN_G2C\020\004\022\026\n\022MESSA" +
      "GE_SIMPLE_G2S\020\005\022\026\n\022MESSAGE_SIMPLE_S2G\020\006\022" +
      "\026\n\022MESSAGE_SIMPLE_C2G\020\007\022\026\n\022MESSAGE_SIMPL" +
      "E_G2C\020\010B\"\n\023io.element.protobufB\013GlobalPr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MessageStream_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MessageStream_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageStream_descriptor,
              new java.lang.String[] { "Type", "RequestData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
